# Generated by Django 3.2.9 on 2021-11-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
